import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/ui/header';
import { TrpcProvider } from '@/trpc/client/trpcProvider';
import { SubHeader } from './components/sub-header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Tractian - FrontEnd Challenge',
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white flex flex-col h-screen `}
      >
        <TrpcProvider>
          <>
            <Header />
            <div className="flex p-4 border-defaultSlate size-full overflow-auto flex-col"> 
              <div className="flex w-full h-full flex-col gap-4 border-defaultSlate border-[1px] rounded-sm p-2 ">
                <SubHeader />

                {children}
              </div>
            </div>
          </>
        </TrpcProvider>
      </body>
    </html>
  );
}
