import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/header';
import { TrpcProvider } from '@/trpc/client/trpcProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Tractian - FrontEnd Challenge',
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-body-slate flex flex-col h-screen`}
      >
        <TrpcProvider>
          <>
            <Header />
            <div className='flex w-full overflow-y-auto p-4 h-full border-slate-500'>{children}</div>
            {/* <div className='p-4 m-4 border-[1px] border-black flex h-full'>{children}</div> */}
          </>
        </TrpcProvider>
      </body>
    </html>
  );
}
